server:
  port: 32011
  jetty:
    threadPool:
          minThreads: 300
          maxThreads: 300
          idleTimeout: 60000

spring:
   application :
        name : ListenToYourself

   cloud:
    stream:
      default-binder: lty-internal-kafka
      bindings:
        # Internal input channels
        consumeOrder:
          binder: lty-internal-kafka
          content-type: text/plain
          group: lty-order
          destination: com.example.lty.order
          consumer:
            header-mode: raw

        # Internal Output channels
        publishOrderInternal:
          binder: lty-internal-kafka
          destination: com.example.lty.order
          content-type: application/json
          producer:
            sync: true
            header-mode: raw

        # External Output channels
        publishOrderExternal:
          binder: lty-external-kafka
          destination: com.example.lty.order
          content-type: application/json
          producer:
            sync: true
            header-mode: raw

      # binder details
      binders:
        lty-internal-kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
        lty-external-kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9093

      # disable auto-commit-offset
      kafka:
        bindings:
          consumeOrder:
            consumer:
              auto-commit-offset: false

couchbase:
    cluster:
      bucketName: listentoyourself
      ip: localhost
      password: listentoyourself



